# Train - Test Split

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split

## 1. Carga del dataset original

In [4]:
df = pd.read_csv('../data/raw/diabetes.csv')
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

## 2. Divisi√≥n en train y test

In [5]:
X = df.drop('Outcome', axis=1)  
y = df['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
df_train = pd.concat([X_train, y_train], axis=1)
df_train.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
60,2,84,0,0,0,0.0,0.304,21,0
618,9,112,82,24,0,28.2,1.282,50,1
346,1,139,46,19,83,28.7,0.654,22,0
294,0,161,50,0,0,21.9,0.254,65,0
231,6,134,80,37,370,46.2,0.238,46,1
340,1,130,70,13,105,25.9,0.472,22,0
535,4,132,0,0,0,32.9,0.302,23,1
306,10,161,68,23,132,25.5,0.326,47,1
718,1,108,60,46,178,35.5,0.415,24,0
90,1,80,55,0,0,19.1,0.258,21,0

In [7]:
df_test = pd.concat([X_test, y_test], axis=1)
df_test

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
668,6,98,58,33,190,34.0,0.430,43,0
324,2,112,75,32,0,35.7,0.148,21,0
624,2,108,64,0,0,30.8,0.158,21,0
690,8,107,80,0,0,24.6,0.856,34,0
473,7,136,90,0,0,29.9,0.210,50,0
...,...,...,...,...,...,...,...,...,...
355,9,165,88,0,0,30.4,0.302,49,1
534,1,77,56,30,56,33.3,1.251,24,0
344,8,95,72,0,0,36.8,0.485,57,0
296,2,146,70,38,360,28.0,0.337,29,1
462,8,74,70,40,49,35.3,0.705,39,0

## 3. Guardamos cada dataset (train y test)

In [8]:
df_train.to_csv('../data/processed/df_train.csv', index=False)

In [9]:
df_test.to_csv('../data/processed/df_test.csv', index=False)